blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/The-CS-Nerds/Library-System-v3/security/advisories/new
    about: Please report security vulnerabilities here.