name: library-system
services:
  library-system-web:
    build:
      context: ../web
    image: library-system-web:latest
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    networks:
      - external-network
      - internal-network
    ports:
      - 3000:3000
    restart: unless-stopped

networks:
  external-network:
    driver: bridge
  internal-network:
    driver: bridge
    internal: true
