name: library-system
services:
  library-system-web:
    build:
      context: ../web
    image: library-system-web:latest
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - external
      - internal
    ports:
      - 3000:3000
    restart: unless-stopped
  
  library-system-db:
    image: postgres:alpine
    restart: always
    networks:
      - internal
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql

networks:
  external:
    driver: bridge
  internal:
    driver: bridge
    internal: true

volumes:
  pgdata: